### PR TITLE
add pagination purging

### PR DESCRIPTION
**Pull request by sejoker**
Fixes https://github.com/cloudflare/Cloudflare-WordPress/issues/337

### CODE REVIEW

**Review by xtuc — APPROVED** [review]

**Comment by scottbuscemi** [comment]
@sejoker This seems to cover /page/*, but are /category-name/* and /tag-name/* pagination covered as well?

**Comment by SmartandCom** [comment]
Pagination problem solved, but it looks like it'as very heavy process in the background, updating or publishing something takes a very long time with last version of the plugin, like if purging is working for ever

**Comment by scottbuscemi** [comment]
> Pagination problem solved, but it looks like it's a very heavy process in the background, updating or publishing something takes a very long time with last version of the plugin, like if purging is working for ever

How many posts do you have? I was afraid this solution would slow things down.

**Comment by SmartandCom** [comment]
7600 posts paginated within 1530 pages
indeed it looks like the cache clearing process is taking a ,lot of time. Our server is powerful enough not  to hang and go to 500 error but it still takes  minutes to process.

**Comment by xtuc** [comment]
We have a tracking issue https://github.com/cloudflare/Cloudflare-WordPress/issues/351 and we are planning to revert the change.

**Pull request merged**
