### PR TITLE
Enforce LF for most filetypes in the repo.

### PR DESCRIPTION
**Pull request by XhmikosR**
This fixes an issue with `composer format` failing on Windows when git's `autocrlf` is set to true and thus the repo line endings are `\r\n`.

### CODE REVIEW

**Comment by thellimist** [comment]
Is there a reason why these files are forced but not all? What would happen to images or similar bytecode files if enforced for all files?

**Comment by XhmikosR** [comment]
Yeah. Because if I use a wildcard, git might mess up some binary files like images. So I prefer to be explicit that sorry.

**Comment by thellimist** [comment]
Is this all the list or are there any other files which mess up? Did you test it on your fork?

**Comment by XhmikosR** [comment]
Only binary files can be messed up. 

Yeah, I tested it and:

```

C:\Users\xmr\Desktop\Cloudflare-WordPress>git status
On branch enforce-lf
Your branch is up-to-date with 'origin/enforce-lf'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility/Tests/sniff-examples/ternary_operator.php
        modified:   vendor/wimg/php-compatibility/Tests/sniff-examples/ternary_operator.php


C:\Users\xmr\Desktop\Cloudflare-WordPress>composer run test
> php vendor/phpunit/phpunit/phpunit
PHPUnit 4.8.27 by Sebastian Bergmann and contributors.

..........................................

Time: 547 ms, Memory: 6.00MB

OK (42 tests, 115 assertions)
```

So for some reason those two files are modified (line endings only); must be that they were using mixed or CRLF when they were committed to the repo.

**Comment by XhmikosR** [comment]
Committed it separately and now:

```
C:\Users\xmr\Desktop\Cloudflare-WordPress>git status
On branch enforce-lf
Your branch is up-to-date with 'origin/enforce-lf'.
nothing to commit, working tree clean
```

**Comment by thellimist** [comment]
993f547 this commit isn't a good solution since it is in vendor folder. The issue can replicate whenever `composer install` is called.

**Comment by XhmikosR** [comment]
I tested just now after doing `composer update`. I removed the vendor folder and reset it.

```
C:\Users\xmr\Desktop\Cloudflare-WordPress>composer run format && composer run test
> php vendor/squizlabs/php_codesniffer/scripts/phpcs -n --standard=phpcs.xml
> php vendor/phpunit/phpunit/phpunit
PHPUnit 4.8.34 by Sebastian Bergmann and contributors.

..........................................

Time: 609 ms, Memory: 6.00MB

OK (42 tests, 115 assertions)

C:\Users\xmr\Desktop\Cloudflare-WordPress>git status
On branch enforce-lf
Your branch is ahead of 'origin/enforce-lf' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

```

So no modified files in vendor for me after `composer update`.

**Comment by XhmikosR** [comment]
[Here](https://github.com/XhmikosR/Cloudflare-WordPress/commit/ad2dd2a5af554b28a6ea80c5ed1dc21a7d357d67) is the update patch.

**Comment by XhmikosR** [comment]
So, are my PRs ever going to be merged? If not just close them.

**Pull request closed without merging**
