### PR TITLE
Improve image compression.

### PR DESCRIPTION
**Pull request by XhmikosR**
Everything is still losslessly compressed.

Before: 36,6 KB (37.560 bytes)
After:  32,2 KB (33.070 bytes)

This is just a followup of #75.

### CODE REVIEW

**Comment by thellimist** [comment]
screen shot 2016-11-21 at 13 25 53

I actually liked 8 bit cloudflare logo 😄 

Unfortunately I'll have reject this PR.

**Comment by XhmikosR** [comment]
Why reject it? It doesn't change the quality. It's lossless. And it's just
a  follow-up patch. The other was successfully merged.

**Comment by jwineman** [comment]
@XhmikosR The cloudflare logo lost resolution.

**Comment by XhmikosR** [comment]
I'll have a look when I'm back bit it shouldn't have. If that's the case
I'll redo this and ping you.

On Nov 21, 2016 20:13, "John Wineman" <notifications@github.com> wrote:

@XhmikosR <https://github.com/XhmikosR> The cloudflare logo lost resolution.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cloudflare/Cloudflare-WordPress/pull/125#issuecomment-262020351>,
or mute the thread

**Comment by XhmikosR** [comment]
@thellimist: please reopen this and should be OK. I kept the SVGs out of it.

**Comment by thellimist** [comment]
@XhmikosR I can't reopen the PR. I'll have to create another PR.

**Comment by XhmikosR** [comment]
Why can't you reopen it? I mean it's the same repo, same branch.

**Comment by thellimist** [comment]
Normally when a contributor comments to the PR they should be able to reopen it. It doesn't allow in this case. The button is disabled.

**Comment by XhmikosR** [comment]
Weird, indeed. See #135 .

**Pull request closed without merging**
