### PR TITLE
Use a space around `.`.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is subjective, but IMO makes it easier to spot where the concatenation is happening.

I also fixed  a small type while at it.

Let me know your thoughts :)

### CODE REVIEW

**Comment by thellimist** [comment]
We're using [PSR2](http://www.php-fig.org/psr/psr-2/) coding style guide. Running `composer format` should tell whether it's supported or not.

**Comment by XhmikosR** [comment]
I don't have composer handy atm, so if you could check it out and let me know that would be sweet.

**Comment by thellimist** [comment]
Try to run `composer test`, `composer format` before you push :wink:

**Comment by XhmikosR** [comment]
The thing is that I'm a Windows user and things don't work out of the box with your setup :/

Anyway, I managed to make things work, and this passes `composer format`.

**Pull request merged**
