### PR TITLE
Replace "CloudFlare" with "Cloudflare".

### PR DESCRIPTION
**Pull request by XhmikosR**
Please test before merging.

The remaining instances are the following:

```
Search "CloudFlare" (9 hits in 4 files)
  C:\Users\xmr\Desktop\Cloudflare-WordPress\cloudflare.loader.php (2 hits)
	Line 5: use CloudFlare\IpRewrite;
	Line 15: $is_cf = $ipRewrite->isCloudFlare();
  C:\Users\xmr\Desktop\Cloudflare-WordPress\compiled.js (1 hit)
	Line 32: }}function p(e){return function(t){t(c()),(0,_.zoneDNSRecordGetAll)(e,function(n,r){t(r?l(e,r.body.result):(0,b.notificationAddClientAPIError)(f(),n))})}}function d(e){return{type:m.DNS_RECORD_UPDATE,name:e}}function h(e,t){return{type:m.DNS_RECORD_UPDATE_SUCCESS,zoneId:e,dnsRecord:t}}function g(){return{type:m.DNS_RECORD_UPDATE_ERROR}}function y(e,t,n){return function(r){r(d(t.name)),(0,_.zoneDNSRecordPatch)({zoneId:e,dnsRecordId:t.id,proxied:n},function(t,n){r(n?h(e,n.body.result):(0,b.notificationAddClientAPIError)(g(),t))})}}Object.defineProperty(n,"__esModule",{value:!0}),n.dnsRecordClearAll=o,n.dnsRecordCreate=i,n.dnsRecordCreateSuccess=a,n.dnsRecordCreateError=s,n.asyncDNSRecordCreate=u,n.dnsRecordFetchList=c,n.dnsRecordFetchListSuccess=l,n.dnsRecordFetchListError=f,n.asyncDNSRecordFetchList=p,n.dnsRecordUpdate=d,n.dnsRecordUpdateSuccess=h,n.dnsRecordUpdateError=g,n.asyncDNSRecordUpdate=y;var v=e("../constants/ActionTypes"),m=r(v),_=e("../utils/CFClientV4API/CFClientV4API"),b=e("./notif...
  C:\Users\xmr\Desktop\Cloudflare-WordPress\compiled.js.map (2 hits)
	Line 1: {"version":3,"sources":["node_modules/browserify/node_modules/browser-pack/_prelude.js","node_modules/browserify/node_modules/browser-resolve/empty.js","node_modules/browserify/node_modules/process/browser.js","node_modules/cf-component-button/lib/Button.js","node_modules/cf-component-button/lib/ButtonGroup.js","node_modules/cf-component-button/lib/index.js","node_modules/cf-component-card/lib/Card.js","node_modules/cf-component-card/lib/CardContent.js","node_modules/cf-component-card/lib/CardControl.js","node_modules/cf-component-card/lib/CardDrawers.js","node_modules/cf-component-card/lib/CardLoadingText.js","node_modules/cf-component-card/lib/CardMessages.js","node_modules/cf-component-card/lib/CardPropTypes.js","node_modules/cf-component-card/lib/CardSection.js","node_modules/cf-component-card/lib/CardToolbar.js","node_modules/cf-component-card/lib/CardToolbarLink.js","node_modules/cf-component-card/lib/index.js","node_modules/cf-component-card/node_modules/cf-component-link/lib/Link.js","n...
	Line 1: {"version":3,"sources":["node_modules/browserify/node_modules/browser-pack/_prelude.js","node_modules/browserify/node_modules/browser-resolve/empty.js","node_modules/browserify/node_modules/process/browser.js","node_modules/cf-component-button/lib/Button.js","node_modules/cf-component-button/lib/ButtonGroup.js","node_modules/cf-component-button/lib/index.js","node_modules/cf-component-card/lib/Card.js","node_modules/cf-component-card/lib/CardContent.js","node_modules/cf-component-card/lib/CardControl.js","node_modules/cf-component-card/lib/CardDrawers.js","node_modules/cf-component-card/lib/CardLoadingText.js","node_modules/cf-component-card/lib/CardMessages.js","node_modules/cf-component-card/lib/CardPropTypes.js","node_modules/cf-component-card/lib/CardSection.js","node_modules/cf-component-card/lib/CardToolbar.js","node_modules/cf-component-card/lib/CardToolbarLink.js","node_modules/cf-component-card/lib/index.js","node_modules/cf-component-card/node_modules/cf-component-link/lib/Link.js","n...
  C:\Users\xmr\Desktop\Cloudflare-WordPress\composer.lock (4 hits)
	Line 34:                     "CloudFlare\\": "src/"
	Line 43:                     "name": "CloudFlare",
	Line 47:             "description": "Library to rewrite CloudFlare IP Addresses to the end-user IP address",
	Line 87:             "description": "A PHP backend for CloudFlare plugins.",
```

which I don't think it's safe to change without breaking things.

Let me know if you need any changes.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I tested this and seems to break a few things. I'm trying to debug it but I can't seem to be able to find the cause so far.

**Comment by jwineman** [comment]
I haven't tested yet but I think a few of the method names reference methods in classes that live in other composer packages.

**Comment by XhmikosR** [comment]
I think I kept those out. See also my first post about the remaining
instances.

**Comment by XhmikosR** [comment]
Also, tests seem to pass on my local dev machine. Something else might be wrong, still trying to figure it out.

**Comment by XhmikosR** [comment]
I'd like to put this on hold until the rest of the PRs are sorted first.

**Comment by thellimist** [comment]
I haven't tested yet. Could you verify that this doesn't break anything?

**Comment by XhmikosR** [comment]
Tests are passing. I don't have a dev server anymore so I can't try it live.

**Comment by thellimist** [comment]
Unfortunately our tests are not enough. I don't trust them. Could you test it? 
The PR can wait until it is tested.

**Comment by XhmikosR** [comment]
Agreed, but since I don't know when I'll have access to a dev server, would be better if one of you tried it :)

**Comment by thellimist** [comment]
The text changes are fine however code changes would break. https://github.com/cloudflare/cloudflare-plugin-backend/blob/master/src/Integration/DataStoreInterface.php#L35 needs to be changed. The backend depends on 3 different plugins: WordPress, CPanel, Magento meaning all 3 plugins should be updated.

**Pull request closed without merging**
