### PR TITLE
SPEED-777: Upgrade cloudflare-plugin-frontend to v3.8.0 (#534)

### LINKED ISSUE #534: Bad Request on Cloudflare Option page
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

Newest

### Cloudflare-WordPress version

Newest

### PHP version

8.1 FPM

### Expected result

No Bad Request

### Actual result

Bad Request Error Message shown. Images and other users reporting it:
https://community.cloudflare.com/t/cloudflare-wordpress-plugin-for-apo-giving-error-of-bad-request/612602/21

### Steps to reproduce

Open Option Page

### Additional factoids

_No response_

### References

https://community.cloudflare.com/t/cloudflare-wordpress-plugin-for-apo-giving-error-of-bad-request/612602/21

### PR DESCRIPTION
**Pull request by aseure**
**🔖 Summary**

By upgrading the compiled files from `cloudflare-plugin-frontend` as of v3.8.0, this commit aims at removing all Railgun-related code, which is now a deprecated Cloudflare feature. This change is proposed due to a `Bad Request` banner which is now shown on the Cloudflare Wordpress plugin page because of a failing call to one of the deprecated Railgun endpoints.

Close #534.

### CODE REVIEW

**Comment by aseure** [comment]
@jacobbednarz I've looked at the git history, but couldn't understand how the `compiled.js.map` is now produced in `cloudflare-plugin-frontend`. My understanding is that we changed the build tool from `gulp` to `npm` and now `yarn` in `cloudflare-plugin-frontend` and the `gulp compress` command is now outdated. If not, could you tell me what's the best way to produce that file. If so, is the `compiled.js.map` file now outdated and could be removed?

**Comment by jacobbednarz** [comment]
as far as i recall, we just need to update the version use by the JS package manager and that should be enough.

**Comment by aseure** [comment]
@jacobbednarz Thing is, there's no JS package manager configuration in this repository (i.e. no `package.json`). All I did in the `cloudflare-plugin-frontend` was to run `yarn build:production` and copy-paste the resulting `compiled.js` file in that repository. However, no `compiled.js.map` got generated, hence my question.

**Review by jacobbednarz — APPROVED** [review]

**Comment by jacobbednarz** [comment]
works for me! the process i was thinking of is for the backend plugin that i already merged in so disregard that.

if you want to in the future, you can pull the frontend code into this repository and have it build in place to save the confusion.

**Pull request merged**
