### PR TITLE
WP Client API uses WP_HTTP class instead of Guzzle.

### LINKED ISSUE #113: Use WP_HTTP instead of Guzzle to make API requests
Hi,
we have a lot of WP websites behind CF and running on Google AppEngine. GAE uses his own library (URLFetch) to make external HTTP calls and hasn't cURL available by default.

We have also few corporate WP installation that doesn't have direct access to internet and they must send requests through a proxy.

The AppEngine Plugin and the `define('WP_PROXY_HOST', '0.0.0.0');` config rules allows WP to manage these situations, but because this plugin use Guzzle instead of the WP_HTTP class, it will not work out of the box in this environments and requires manual patches.

Could this plugin be updated to use the WP_HTTP Class to better follow the WP guidelines?

Thanks for the great work.

### PR DESCRIPTION
**Pull request by XhmikosR**
Removes the php-curl dependency.

Fixes #113.

This is #134, formatted, rebased and squashed.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@thellimist @jwineman: can you please have a look at my PRs? It's annoying having to rebase them :/

**Comment by thellimist** [comment]
@XhmikosR Thanks for fixing the the conflictions.

**Comment by jb510** [comment]
So... the Guzzle dependency was removed, and composer.json updated...  but Guzzle is still checked in.  Is there a reason it hasn't been removed?

**Comment by jwineman** [comment]
Good catch @jb510 - addressing this in https://github.com/cloudflare/Cloudflare-WordPress/pull/174.

**Pull request merged**
