### PR TITLE
Remove trailing spaces and convert tabs to spaces.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by thellimist** [comment]
This will conflict with everything. I'll decline.

**Comment by XhmikosR** [comment]
What exactly is **everything**?

**Comment by thellimist** [comment]
Changes except for the md files. I'll a few changes this week. Afterwards we can check again.

**Comment by XhmikosR** [comment]
Well, there's no need to close it then. Just reopen it and ping me to rebase after you push your changes.

**Comment by XhmikosR** [comment]
@thellimist: can you reopen this now? I've rebased my branch so it should have no conflicts.

**Comment by thellimist** [comment]
`The master branch was force-pushed or recreated.`. That's interesting. Github doesn't allow to reopen.

**Comment by XhmikosR** [comment]
Should I make a new PR then?

**Comment by thellimist** [comment]
No need. It's just indentation fixes.

**Pull request closed without merging**
