### PR TITLE
Added my username

### PR DESCRIPTION
**Pull request by manatarms**
Yay.

### CODE REVIEW

**Comment by thellimist** [comment]
The name over there is WordPress account. You can see it in this page

https://en-gb.wordpress.org/plugins/cloudflare/advanced/

FYI the nick you changed is the account tag rather than the account name. I'd suggest getting and account with the same tag

**Comment by jwineman** [comment]
Welcome to the team, guy.

**Comment by manatarms** [comment]
@thellimist Not quite sure what you mean, but this is the account I have right now https://profiles.wordpress.org/manatarms. Is this what you meant ?

**Comment by thellimist** [comment]
Correct `@manatarms on WordPress.org`.

**Pull request merged**
